services:
  - type: web
    name: fastapi-backend
    env: python
    buildCommand: ""
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: APPWRITE_PROJECT_ID
        value: your_project_id
      - key: APPWRITE_API_KEY
        value: your_api_key
      - key: APPWRITE_DATABASE_ID
        value: your_db_id
      - key: APPWRITE_ENDPOINT
        value: https://cloud.appwrite.io/v1
